### PR TITLE
Test backfill

### PR DESCRIPTION
**Pull request by jimszalew**
LIST OF CHANGES:
added brakeman and rubycritic gems and bundled

THINGS I'M UNSURE ON:
not sure if these gems will get CI to pass, was suggested in the details of the travis check

RSPEC GREEN?
YES

*MENTION GROUP MEMBER TO REVIEW PR*

### CODE REVIEW

**Comment by jimszalew** [comment]
Travis says its okay! I added the gems 'rubycritic' and 'brakeman' becasue Travis seemed to want them, and he was okay with it.

**Review by mimizotti — COMMENTED** [review]
This looks good. Thanks for doing this, @jimszalew!

**Comment by vaidashi** [comment]
anything that helps our test coverage jim

**Review by vaidashi — APPROVED** [review]
upped the coverage, way to go Jim

**Pull request merged**
